apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-sync-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["sh",  "exit 1"]
      restartPolicy: Never
  backoffLimit: 1
